
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar/page";
import Footer from "@/components/footer/page";
import { ToastContainer } from "react-toastify";


import { FriendProvider } from "@/components/context/FriendContext";





const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme='light'
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >

    

      <body className="min-h-full flex flex-col">
    <FriendProvider>
          <NavBar></NavBar>
       
         <main>
         
          
            {children}

            <ToastContainer />
           
         </main>
          <Footer></Footer>
    </FriendProvider>


       
        </body>
    </html>
  );
}
